name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

      - name: Force push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://snehangshu270219:$HF_TOKEN@huggingface.co/spaces/snehangshu270219/Customer_Churn_prediction main
